disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - missing_docs

included:
  - Sources
  - Tests

excluded:
  - .build

line_length:
  warning: 150
  error: 200

type_name:
  min_length: 3
  max_length: 50

identifier_name:
  min_length: 2
